server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
spring:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
      poll-interval: 1000
      quiet-period: 400
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  show-sql: true
paypal:
  client:
    id: AWdiwaRVbO3Mj2QgQ2B16u5wPGhDUJ4H4Ipe5gBT479hhj4nyM-sdLvrQcT8HHRCpFPLGney9wQfmJ21
    secret: EB2IEw7trGpPoB16fDje13tHTVccC6ilOuPhx1PQYSXXsu9UPKXgOj25q0iOfpp64Zd80LbCFn9K-tjQ
  mode: sandbox